export const Skill_data = [
    {
        skill_name: "Html 5",
        image: "html.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Css",
        image: "css.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Java Script",
        image: "js.png",
        width: 65,
        height: 65,
    },
    {
        skill_name: "Tailwind Css",
        image: "tailwind.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "React",
        image: "react.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Redux",
        image: "redux.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "React Query",
        image: "reactquery.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Type Script",
        image: "ts.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Next js 13",
        image: "next.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Framer Motion",
        image: "framer.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Stripe Payment",
        image: "stripe.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Node js",
        image: "node-js.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Mongo db",
        image: "mongodb.png",
        width: 40,
        height: 40,
    },
    {
        skill_name: "Figma",
        image: "figma.png",
        width: 50,
        height: 50,
    },
    {
        skill_name: "OpenAI API",
        image: "openai.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Gemini API",
        image: "gemini.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Groq",
        image: "groq.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Perplexity AI",
        image: "perplexity.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "Notion AI",
        image: "notion.png",
        width: 80,
        height: 80,
    },
    {
        skill_name: "MS Office",
        image: "office.png",
        width: 80,
        height: 80,
    },
];
